'use client';
import './globals.css';
import { Roboto } from 'next/font/google';
import StyledComponentsRegistry from './lib/registry';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const robot = Roboto({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html className={robot.className}>
			<StyledComponentsRegistry>
				<body>
					<Header />
					{children}
					<Footer />
				</body>
			</StyledComponentsRegistry>
		</html>
	);
}
